### ISSUE TITLE
handle the instance size 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/gwb#37]
@vogtpet, For some computation the instance is too small to run the GWB module, which is well handled by the GWB CLI as it writes in the logs that some problems prevent the computation to occurs. As I have access to the instance status I would like t run a prelaunch analysis to know wether or not the instance is too small and catch the error before it occurs. 

By doing so I would be able to display a way more convenient error message. 

Do you have an idea of the complexity of all these algorithm and the amont of memory they all required (with respect to the size of the initial image) ?

**Comment by vogtpet** [comment]
Each GWB module runs a series of pre-computation tests for each input image, verifying that
- required colortables and input-parameter files are in place and in the correct format
- the image format (must be datatype byte)
- the image type (must be of type tif and single channel)
- appropriate min/max value in the image
- presence of required foreground, background (and optional other) values
- appropriate naming scheme of input/output directory
- detect available free RAM and cross-check this with the maximum RAM amount needed for processing the input image of size X mb

Only if all tests are ok, the computation will start. If not, the error is reported in the log-file. Meaning, the prelaunch analysis is already in place inside the IDL-scripts that are executed. 
In principle, one could do all those "compliance tests" in dedicated bash-scripts and in case the input image passes these tests, then launch the existing IDL-script without doing the compliance tests (if the IDL script detects the file <input_dir>/nocheck.txt, the IDL-script will automatically skip the compliance tests).   

However, the compliance tests are not identical for all modules, so one would have to recode many things in bash or another language. Quite some work and somehow duplicating an already working setup...
What exactly is the issue here? I assume the problem only occurs for memory-intensive computations (MSPA and maybe FAD), or? If the error is about insufficient memory then the following could give a guideline for MSPA:
The maximum size of a square image of dimension Z (ZxZ pixels) that can be processed is: Z = sqrt(1024^3 / 20 * RAM).
For example if you have 14 GB free RAM; then Z = sqrt(1024^3/20*14) = 27400 pixels, meaning you can process an image of no more than 27400×27400 pixels.

The attached bash-script shows how we did the MSPA in bash only, earlier called the "fragmentation tool":
Line 90-111 show how to calculate the maximum supported files size of the input image for MSPA-processing on a given instance.
Line 118, 121 and then 144-158 get the input image size and compare it to the amount of free RAM.

If the problem only occurs for MSPA I can write a brief bash-startup check for file-size/memory compatibility that you could invoke before launching the GWB-MSPA module, let me know.

[gtb-mspa.txt](https://github.com/12rambau/gwb/files/6311456/gtb-mspa.txt)

**Comment by 12rambau** [comment]
yes that's effectively a lot of work to reimplement all that. 

I normally display the log output in case of crash (If only a log file is produce I assume that the computation failed) and This information is displayed inside. 

@lecrabe did a computation with the previous implementation and realized that it was lacking memory and they were nothing preventing him from launching it anyway. 

I would advocate in favor of the launch anyway and read the logs that are displayed for informations

**Comment by vogtpet** [comment]
I don't understand:
- lecrabe did a computation (of what - MSPA?) 
- with the previous implementation (fragmentation tool?)

The GWB-log file is always generated, if the computation was successful or not. The log-file in the directory output includes details (and error info if encountered) of the computation process.  If you launch GWB-MSPA and the script detects that the system has insufficient memory then the log-file will contain this message:
_Skipping invalid input (wrong dimensions, image too big, not enough RAM): _name of the input image__

If the log-file shows this message then the current instance has insufficient (free) memory. The current instance should be stopped and a new instance with more memory should be started. If needed, we could run a small additional script (as I suggested before) that would calculate the amount of memory needed to process MSPA for _name of the input image_, so the user will have an indication to choose an instance with appropriate memory amount. Please let me know if such a script is considered meaningful keeping in mind that this would only address MSPA...

**Comment by 12rambau** [comment]
I meant a previous release (the one from 2 days ago). I know that log file is always generated. It's just that GWB command doesn't interact well with python so I needed to find tricks to know wether something happened or not. The solution I came up with is the following : 
```
IF only a log file is produced, something went wrong THEN display the log to the user as an error message ELSE continue 
```

knowing this the message shows several possible bugs : wrong dimensions, image too big, not enough RAM and what I would need is precisely what make it stop. But I must confess that I don't want to copy/paste things that are already coded. 

So at the moment it will stay as it is

**Comment by vogtpet** [comment]
ok, that makes sense :-)
Still, that pre-script with imagesize/memory check for MSPA might be a valuable addition, I will think about this a bit more tomorrow...

**Comment by vogtpet** [comment]
after some more thinking: such a pre-script wouldn't do anything different than what the current IDL-script for MSPA already does. If an image is too large for processing on a given instance, the current MSPA IDL-script will report that " the image is too large for processing", write this to the log-file and exit without doing any MSPA-processing. A potential improvement could be that the error message could specify how much RAM is required to process the given image. The user would then have an idea which instance to choose to process the given image. I will see how to best implement this in an updated version.

**Comment by 12rambau** [comment]
Considering the surfaces we want to process I assume that it will be problem for all of them
