### ISSUE TITLE
add the no_check option ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/gwb#5]
If I create the byte files myself I can run the process with the no_check.txt empty file in my list. 
The the CLI will not provide any text before starting the computation

It's dangerous as it could lead to unexplained crash but can really save time

**Comment by vogtpet** [comment]
the "no_check.txt" trick is designed for advanced users who know *exactly* what they do and who are 100% sure that their input files are correct, so they can skip the initial input file verification step and save some time. I suggest to not use this hack in the UI implementation, also because only one file is processed there so not much time is lost. 
People who want to do mass-processing can use it in the cmd-line setup if they want to.
